export const BOOKING_CONSTRAINTS = {
  MIN_HOURS_BEFORE_BOOKING: 2,
  MAX_BOOKINGS_PER_WEEK: 3,
  SLOTS_PER_MACHINE: 2
};

export const BUSINESS_HOURS = {
  START: 9,
  END: 17,
  SLOT_DURATION: 30
};

export const AUTH_CONSTANTS = {
  OTP_EXPIRY_MINUTES: 5,
  TEST_OTP: '111111'
};